dist: xenial
language: ruby
jdk: openjdk8

addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.bintray.com/sbt/debian /'
        key_url: 'https://bintray.com/user/downloadSubjectPublicKey?username=sbt'
    packages:
      - sbt=1.4.1
      - libgmp10
      - latex-cjk-all
      - texlive-full

before_script:
  - wget https://github.com/jgm/pandoc/releases/download/2.3.1/pandoc-2.3.1-1-amd64.deb
  - sudo dpkg -i pandoc-2.3.1-1-amd64.deb
  - rm pandoc-2.3.1-1-amd64.deb
  - export JVM_OPTS="-Dfile.encoding=UTF-8 -Xmx1G -Xms1G -server -XX:ReservedCodeCacheSize=128M"

# Use `/usr/bin/sbt` that we manually installed
script: /usr/bin/sbt -Dsbt.website.generate_pdf scalafmtSbtCheck scalafmtCheck test:scalafmtCheck scripted makeSite

after_success: .travis/publish-site.sh

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete

cache:
  - apt
  - directories:
    - $HOME/.cache/coursier/v1
    - $HOME/.ivy2/cache
    - $HOME/.sbt
